import type { LessonMeta } from "@/types/lesson";

export const lessonConfig: LessonMeta[] = [
  {
    slug: "what-is-money",
    title: "What Is Money?",
    summary: "Trace why societies adopt money and what properties make it useful.",
    duration: "8 min",
    order: 1,
    section: "Foundations",
  },
  {
    slug: "the-problem-with-traditional-money",
    title: "The Problem With Traditional Money",
    summary: "See where inflation, intermediaries, and changing rules make modern money fragile.",
    duration: "9 min",
    order: 2,
    section: "Foundations",
  },
  {
    slug: "what-is-bitcoin",
    title: "What Is Bitcoin?",
    summary: "Learn the core idea behind a scarce, open monetary network.",
    duration: "12 min",
    order: 3,
    section: "Foundations",
  },
  {
    slug: "who-created-bitcoin",
    title: "Who Created Bitcoin?",
    summary: "Understand Satoshi Nakamoto's role and why Bitcoin was built to outlive its founder.",
    duration: "7 min",
    order: 4,
    section: "Foundations",
  },
  {
    slug: "why-does-bitcoin-matter",
    title: "Why Does Bitcoin Matter?",
    summary: "Explore why scarcity, openness, and self-custody make Bitcoin a serious monetary idea.",
    duration: "8 min",
    order: 5,
    section: "Foundations",
  },
  {
    slug: "how-bitcoin-works-simple-view",
    title: "How Bitcoin Works (Simple View)",
    summary: "Learn the basic flow of transactions, blocks, and verification without technical overload.",
    duration: "9 min",
    order: 6,
    section: "Core Concepts",
  },
  {
    slug: "the-blockchain-explained",
    title: "The Blockchain Explained",
    summary: "Understand how blocks link together and why that shared record matters.",
    duration: "8 min",
    order: 7,
    section: "Core Concepts",
  },
  {
    slug: "what-makes-bitcoin-secure",
    title: "What Makes Bitcoin Secure?",
    summary: "See how incentives, verification, and decentralization work together to protect the network.",
    duration: "9 min",
    order: 8,
    section: "Core Concepts",
  },
  {
    slug: "why-bitcoin-is-scarce",
    title: "Why Bitcoin Is Scarce (21 Million)",
    summary: "Explore the supply cap and why predictable issuance is central to Bitcoin's design.",
    duration: "8 min",
    order: 9,
    section: "Core Concepts",
  },
  {
    slug: "decentralisation-explained",
    title: "Decentralisation Explained",
    summary: "Learn what decentralization means in practice and why it matters for money.",
    duration: "8 min",
    order: 10,
    section: "Core Concepts",
  },
  {
    slug: "what-is-a-bitcoin-wallet",
    title: "What Is a Bitcoin Wallet?",
    summary: "Learn what a wallet really does and why it is about keys, not coins sitting in an app.",
    duration: "8 min",
    order: 11,
    section: "Wallets & Ownership",
  },
  {
    slug: "custodial-vs-non-custodial-wallets",
    title: "Custodial vs Non-Custodial Wallets",
    summary: "Compare convenience and control so you can understand the main wallet tradeoff.",
    order: 12,
    duration: "8 min",
    section: "Wallets & Ownership",
  },
  {
    slug: "private-keys-explained",
    title: "Private Keys Explained",
    summary: "See why private keys define ownership and why protecting them is everything.",
    duration: "9 min",
    order: 13,
    section: "Wallets & Ownership",
  },
  {
    slug: "seed-phrases",
    title: "Seed Phrases",
    summary: "Understand what a recovery phrase is, why it matters, and how beginners should treat it.",
    duration: "8 min",
    order: 14,
    section: "Wallets & Ownership",
  },
  {
    slug: "how-to-store-bitcoin-safely",
    title: "How to Store Bitcoin Safely",
    summary: "Learn the core habits that keep bitcoin secure over the long term.",
    duration: "9 min",
    order: 15,
    section: "Wallets & Ownership",
  },
  {
    slug: "transactions",
    title: "Transactions",
    summary: "See how Bitcoin transactions move value and settle on-chain.",
    duration: "11 min",
    order: 16,
  },
  {
    slug: "security",
    title: "Security",
    summary: "Build safe habits for backups, scams, and device hygiene.",
    duration: "9 min",
    order: 17,
  },
];
